cluster.name: RealTimeCongress

index:
  number_of_shards: 5 # default
  number_of_replicas: 1 # default

path:
  data: /var/lib/elasticsearch
  work: /mnt

http:
  port: 9200 # default

bootstrap:
  mlockall: true