# used in any part of cluster

cluster.name: RealTimeCongress2

index:
  number_of_shards: 5 # default
  number_of_replicas: 1 # default

path:
  data: /var/lib/elasticsearch
  work: /mnt

http:
  port: 3145

bootstrap:
  mlockall: true


node.master: true # default
node.data: true # default


# depends on cloud-aws plugin being installed

discovery.type: ec2
discovery.ec2.groups: elasticsearch
discovery.ec2.tag.app: rtc
discovery.ec2.tag.active: true

cloud:
  aws:
    access_key: # fill in
    secret_key: # fill in